# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0011_auto_20160730_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_id', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20, null=True)),
                ('loan_amount_per_capita', models.CharField(max_length=20, null=True)),
                ('avg_loan_per_trade', models.CharField(max_length=20, null=True)),
                ('invest_amount_per_capita', models.CharField(max_length=20, null=True)),
                ('avg_invest_per_trade', models.CharField(max_length=20, null=True)),
                ('max_borrower_ratio', models.CharField(max_length=20, null=True)),
                ('topten_borrowers_ratio', models.CharField(max_length=20, null=True)),
                ('overdue_project_amount', models.CharField(max_length=20, null=True)),
                ('avg_interest_rate', models.CharField(max_length=20, null=True)),
                ('avg_borrow_period', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'aif_monthly_basic',
            },
        ),
        migrations.RemoveField(
            model_name='basic',
            name='accum_default_rate',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='avg_borrow_period',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='avg_invest_per_trade',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='avg_loan_per_trade',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='bad_debt_rate',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='customer_complaints',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='customer_complaints_solve',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='financial_leverage',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='invest_amount_per_capita',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='loan_amount_per_capita',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='max_borrower_ratio',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='repaid_amount',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='three_month_overdue_rate',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='topten_borrowers_ratio',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='topten_investor_ratio',
        ),
        migrations.AddField(
            model_name='basic',
            name='different_borrower_amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basic',
            name='different_investor_amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basic',
            name='unconventional_turnover_amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='monthlybasic',
            unique_together=set([('plat_id', 'date')]),
        ),
    ]
