# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0012_auto_20160928_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='project',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='spider',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
