# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0013_auto_20161017_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='revenue',
        ),
    ]
